### ISSUE TITLE
SternalBoard 3.0.0

### ISSUE THREAD

**Issue by xIsm4** [ShieldCommunity/SternalBoard#44]
I know we have left this plugin a bit aside, but we have been working privately and talking about it.

- Implement Tab (Header and footer) at packet-level supporting current versions
- Implement bossbar system 
- Implement Nametag system
- Totally refactor internally (because SternalBoard was designed only for board system)

If you have other feature request, comment it.

**Comment by Xxyuri2005xX** [comment]
- Custom placeholders creation to use with SternalBoard (example: **%online%** -> returns the number of online players) with as parameters in the creation: placeholder (%time%), update(in seconds, 1), return (the part of the code that returns what is of interest)
- Placeholders update method

**Comment by xIsm4** [comment]
> * Custom placeholders creation to use with SternalBoard (example: **%online%** -> returns the number of online players) with as parameters in the creation: placeholder (%time%), update(in seconds, 1), return (the part of the code that returns what is of interest)
> * Placeholders update method

I think that custom placeholders is good for specific boars settings, mostly like any server uses placeholderapi and the %online% seems redundant.

Ill take a look on the New method used

**Comment by tomkeuper** [comment]
> I think that custom placeholders is good for specific boars settings, mostly like any server uses placeholderapi and the %online% seems redundant.
> 
> Ill take a look on the New method used

Just hooking in because I was interested in this aswell. The ability ro register custom placeholders is quite usefull definitly with the API, because plugins and addons can use this to show more advanced placeholders that need specific data. and with this provides different options like event based triggers for updating the placeholder value or even updating the function behind it. 

I've used a different plugins api in the past where you could register placeholders internally thru callables, it was possible to update those placeholders aswell with a trigger so I could make sure that all placeholders are updated as I want based on the code thats running at that time. In my opnion a extremely usefull feature for other developers aswell.

**Comment by jonakls** [comment]
Hi, I just enabled discussions to expand this thread in a more appropriate place. Please, go [here](https://github.com/ShieldCommunity/SternalBoard/discussions/48)
